version: "2"

services:
  zookeeper:
    image: blacktop/kafka
    command: zookeeper-server-start.sh config/zookeeper.properties
    ports:
      - 2181:2181
    networks:
      - kafka
  kafka:
    image: blacktop/kafka
    environment:
      - KAFKA_HEAP_OPTS=-Xmx2G -Xms2G
    ports:
      - 9092:9092
    links:
     - zookeeper
    volumes:
      - kafka-logs:/tmp/kafka-logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka

volumes:
  kafka-logs:

networks:
  kafka:
    driver: bridge
